# Generated by Django 2.0.7 on 2018-08-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('register_time', models.DateTimeField(verbose_name='register time')),
            ],
        ),
    ]
